### ISSUE TITLE
ScoreSheet should sort by users' Score

### ISSUE THREAD

**Issue by rruenroeng** [DarrenZLew/FantasyFitness-1.0#29]
**What's Wrong?**
Currently the scores on the scoresheet are displayed in the order that they are loaded from the back-end. 

**What do I Expect to Happen?**
We would want them to be sorted from highest to lowest score. 

**Suggested Fix**
This could be done on the back-end. When the data is being retrieved, it would be sorted. When a user saves their data, the application will also reload its state from the back-end.

**Supporting Information**

**Comment by DarrenZLew** [comment]
Makes more sense to do this on the front end.

**Comment by DarrenZLew** [comment]
Added in branch iss29

**Comment by DarrenZLew** [comment]
Pull Request accepted in iss29
