### ISSUE TITLE
Combining frontend and backend

### ISSUE THREAD

**Issue by sandasai** [DarrenZLew/FantasyFitness-1.0#31]
**What's Wrong?**
Current app is split into two separate ones for client and server. We need to link the two together to have them communicate.

**What do I Expect to Happen?**
When we deploy the app, the client should be able to communicate with the backend.

**Suggested Fix**
Either run a single application that serves both frontend and back. Or deploy two different apps.

**Supporting Information**
https://daveceddia.com/create-react-app-express-production/

https://github.com/facebookincubator/create-react-app/issues/639

**Comment by DarrenZLew** [comment]
Completed. Check package.json of root folder. This links to client package.json and server package.json.
