### ISSUE TITLE
Create Challenge Movement In ScoreForm

### ISSUE THREAD

**Issue by rruenroeng** [DarrenZLew/FantasyFitness-1.0#38]
**What's Wrong?**
We don't have a means to incorporate the challenge movement.

**What do I Expect to Happen?**
The challenge movement is a key component of FF.

**Suggested Fix**
The Head to Head movement will likely need it's own handling/section. It should either respect a schedule which we store in a separate table or we need to think critically on how to handle this type of data.

**Supporting Information**
Will need to add issues for displaying data after it has been made.

**Comment by DarrenZLew** [comment]
We can simply add the challenge movement to the form underneath its own category. I've created a pull request under iss38 for this.

**Comment by DarrenZLew** [comment]
Completed in branch iss38
