### ISSUE TITLE
Select through multiple forms on ScoreForms page

### ISSUE THREAD

**Issue by DarrenZLew** [DarrenZLew/FantasyFitness-1.0#49]
**What's Wrong?**
Currently unable to select a different league's form from the ScoreForms page.

**What do I Expect to Happen?**
Ability to tab or select a different league's form to submit data.

**Suggested Fix**
Add frontend design for selecting a different league's form on ScoreForms.

**Supporting Information**

**Comment by rruenroeng** [comment]
Don't forget about the user experience of being able to select a different leagues ScoreForm. They should see a different leagues Scoresheet and such if they toggle the League. The league toggle may best be handled via a "Hamburger" on the overall toolbar. Similar to the way it highlights the active tab, it would change its title to the active leagues title. Meaning that leagues will have titles. :)

**Comment by rruenroeng** [comment]
After our most-recent touch-base with Alex and based on the feedback from the others during our TB about  the back-end. I think we've come to the conclusion that our players will not be seeing different leagues and that each activity will count for all leagues.
