### ISSUE TITLE
Display Times as HH:MM on scoreSheet

### ISSUE THREAD

**Issue by rruenroeng** [DarrenZLew/FantasyFitness-1.0#50]
**What's Wrong?**
Having times on two separate rows makes them more difficult to compare.

**What do I Expect to Happen?**
 Providing a single row with both minutes and hours would be easier to digest by end users.

**Suggested Fix**
Display the times as Hours":"Minutes

**Supporting Information**

**Comment by DarrenZLew** [comment]
To update from ## hrs ## mins to HH:MM, we simply need to convert single digit HH and MM using code below:
 if (hr < 10) {
	hr = '0' + hr
}
if (min < 10) {
	min = '0' + min
}

Added pull request for branch iss50.
