### ISSUE TITLE
Make ScoreForm more mobile responsive

### ISSUE THREAD

**Issue by DarrenZLew** [DarrenZLew/FantasyFitness-1.0#52]
**What's Wrong?**
ScoreForm currently doesn't look great as a responsive component. We can make it look nicer and be more user friendly.

**What do I Expect to Happen?**
Mobile users should like the ScoreForm and find it easy to input data.

**Suggested Fix**
Make ScoreForm more mobile responsive.

**Supporting Information**

**Comment by rruenroeng** [comment]
I checked it out. I think it's nice.

Here are some things that could use work:
1) The net score right now is hidden behind the submit and information button. I accidentally proced the information animation a bunch of times before I 1) Understood what was happening and 2) Followed what I was supposed to do with it. 
How can we make this more intuitive?

2) I am clicking on the activity name and getting the information often. Is there anyway we can change the box to display the information and submit button? Would that behave nicely?

3) I really don't like that I have to click the far left side of the screen to get rid of the information bubble. Can we have the information expand under the activity box perhaps? Maybe it does this anytime you're scoring anyway. When you hit submit, it also makes the expanded thing contract. Or when you hit the activity a second time. This would prevent where you're clicking to get the info from moving around the screen/getting hidden behind pop-ups. 

Why are we having the submit button on the side of the screen again? 
With the way you have things setup right now, if I put a +55 on an exercise and then move on to the next exercise without submitting the last, it shows the +55 without a warning that states that I didn't submit the new score. I think people with make mistakes with this.

I can think of two potential solutions that might make this more usable:
1) A static submit button that's always on the bottom of the mobile screen that will submit all of the data. 
2) Making the submit button pop you to the next exercise when it has something to save and having it skip you to the next selectable field when there isn't data to submit. This might make navigation between the fields quicker.

Could we draw out some options sometime? I think Alex and Sanda might have some good opinions also.
